pekko {
  loglevel = INFO

  actor {
    provider = cluster
    serialization-bindings {
      "pcd.alarm.system.domain.CborSerializable" = jackson-cbor
    }
  }

  remote.artery {
    transport = tcp
    canonical {
        hostname = ${?NODE_HOST}
        port = ${?NODE_PORT}
    }
  }

  cluster {
    seed-nodes = [
      "pekko://"${cluster.name}"@"${cluster.seed-host}":"${cluster.seed-port}
    ]
    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"

    roles = [${?node.role}]
  }
}

# Networking identity of this node. Overridable via env vars.
node {
  host = "127.0.0.1"
  host = ${?NODE_HOST}

  port = 2551
  port = ${?NODE_PORT}

  role = ${?NODE_ROLE}
}

# Identity of the cluster and of the node used to bootstrap it (seed node).
cluster {
  name = "SmartHomeAlarmSystem"
  name = ${?CLUSTER_NAME}

  seed-host = "127.0.0.1"
  seed-host = ${?SEED_HOST}

  seed-port = 2551
  seed-port = ${?SEED_PORT}
}
